name: automerge
on:
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        uses: TRANZACT/Platforms.gitflow-automerge-action@v0.1.0
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
